spring:
  redis:
    password: 123456
    #单机redis
    host: 162.14.96.42
    port: 6379
    ##哨兵配置
#    sentinel:
#      master: mymaster
#      nodes: 192.168.1.11:26379,192.168.1.23:26379,192.168.1.32:26379
    ##
    jedis:
      pool:
        ### 连接池最大连接数（使用负值表示没有限制）
        max-active: 9
        ### 连接池最大阻塞等待时间
        max-wait: -1
        ### 连接池最大空闲连接数
        max-idle: 9
        ### 连接池最小空闲连接数
        min-idle: 0
    ### Redis数据库索引
    database: 0
    ### 连接超时时间
    timeout: 60000

springdoc:
  api-docs:
    #是否开启文档功能
    enabled: true
    #swagger后端请求地址
    path: /api-docs
  swagger-ui:
    #自定义swagger前端请求路径，输入http：127.0.0.1:8080/test会自动重定向到swagger页面
    path: /apidoc
  #包扫描路径
  packages-to-scan: com.example.demo.controller